# Site
title: Lab Spaces
cover: "/assets/cover/cover.jpg"

# URL
url: http://alab.space
baseurl: ''
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4444

# Data
social:
  facebook_url: "https://www.facebook.com/thiago.hersan"
  twitter_url: "https://www.twitter.com/thiagohersan"
  twitter_user: "@thiagohersan"
